{
 "title": "Experiments",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "experiment_name",
    "label": "Experiment Name",
    "query": {
     "query": "query_result({__name__=~\"filatik_go_password_keeper_experiment_.*\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Experiments Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Experiments",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum by (experiment_name) ( \r\n    increase(\r\n      filatik_go_password_keeper_experiment_distributions_total[$__range]) ) > bool 0, \r\n      \"is_distribution\",\"1\",\"\",\"\" ) \r\nor \r\nlabel_replace( \r\n  sum by (experiment_name) ( \r\n    increase(\r\n      filatik_go_password_keeper_experiment_executions_total[$__range]) ) > bool 0, \r\n      \"is_execution\",\"1\",\"\",\"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Experiments Distribution (Number By Interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_distributions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__rate_interval]\r\n    )\r\n  ),\r\n  \"experiment_name\", \"TOTAL\", \"\", \"\"\r\n)\r\nor\r\nsum by (experiment_name) (\r\n  increase(\r\n    filatik_go_password_keeper_experiment_distributions_total{\r\n      experiment_name=~\"$experiment_name\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Experiments Execution (Number By Interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_executions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__rate_interval]\r\n    )\r\n  ),\r\n  \"experiment_name\", \"TOTAL\", \"\", \"\"\r\n)\r\nor\r\nsum by (experiment_name) (\r\n  increase(\r\n    filatik_go_password_keeper_experiment_executions_total{\r\n      experiment_name=~\"$experiment_name\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Experiment: $experiment_name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "experiment_name" },
  {
   "title": "Distribution (Percentage By Range)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\r\n  100 *\r\n  sum by (branch_name) (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_distributions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__range]\r\n    )\r\n  )\r\n  /\r\n  scalar(\r\n    sum(\r\n      increase(\r\n        filatik_go_password_keeper_experiment_distributions_total{\r\n          experiment_name=~\"$experiment_name\"\r\n        }[$__range]\r\n      )\r\n    )\r\n  ),\r\n  100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution (Percentage By Interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(\r\n  100 *\r\n  sum by (branch_name) (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_distributions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__rate_interval]\r\n    )\r\n  )\r\n  /\r\n  scalar(\r\n    sum(\r\n      increase(\r\n        filatik_go_password_keeper_experiment_distributions_total{\r\n          experiment_name=~\"$experiment_name\"\r\n        }[$__rate_interval]\r\n      )\r\n    )\r\n  ),\r\n  100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution (Number By Interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_distributions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__rate_interval]\r\n    )\r\n  ),\r\n  \"branch_name\", \"TOTAL\", \"\", \"\"\r\n)\r\nor\r\nsum by(branch_name) (\r\n  increase(\r\n    filatik_go_password_keeper_experiment_distributions_total{\r\n      experiment_name=~\"$experiment_name\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution (Repcentage By Range)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\r\n  100 *\r\n  sum by (branch_name) (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_executions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__rate_interval]\r\n    )\r\n  )\r\n  /\r\n  scalar(\r\n    sum(\r\n      increase(\r\n        filatik_go_password_keeper_experiment_executions_total{\r\n          experiment_name=~\"$experiment_name\"\r\n        }[$__rate_interval]\r\n      )\r\n    )\r\n  ),\r\n  100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution (Percentage By Interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "clamp_max(\r\n  100 *\r\n  sum by (branch_name) (\r\n    increase(\r\n      filatik_go_password_keeper_experiment_executions_total{\r\n        experiment_name=~\"$experiment_name\"\r\n      }[$__rate_interval]\r\n    )\r\n  )\r\n  /\r\n  scalar(\r\n    sum(\r\n      increase(\r\n        filatik_go_password_keeper_experiment_executions_total{\r\n          experiment_name=~\"$experiment_name\"\r\n        }[$__rate_interval]\r\n      )\r\n    )\r\n  ),\r\n  100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution (Number By Interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum by (branch_name) (\r\n  increase(\r\n    filatik_go_password_keeper_experiment_executions_total{\r\n      experiment_name=~\"$experiment_name\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}