version: "2"
linters:
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
    - zerologlint
  settings:
    # arangolint:
    # asasalint:
    #   ignore-test: false
    # asciicheck:
    # bidichk:
    # bodyclose:
    # canonicalheader:
    # containedctx:
    # contextcheck:
    # copyloopvar:
    # cyclop:
    # decorder:
    depguard:
      rules:
        main:
          list-mode: original
          files:
            - "**/cmd/**/main.go"
            - "**/cmd/**/main.go"
          allow:
            - "github.com/mr-filatik/go-password-keeper/internal/client"
            - "github.com/mr-filatik/go-password-keeper/internal/server"
          deny: []
    # dogsled:
    # dupl:
    # dupword:
    # durationcheck:
    # embeddedstructfieldcheck:
    # err113:
    # errcheck:
    # errchkjson:
    # errname:
    # errorlint:
    # exhaustive:
    exhaustruct:
      exclude:
        - '(?i)^(?:.*/)?(?:[^.]+\.)?(mock|Mock)\w*$'
        - '(?i)^(?:.*/)?(?:[^.]+\.)?(fake|Fake)\w*$'
    # exptostd:
    # fatcontext:
    forbidigo:
      forbid: # Default: ["^(fmt\\.Print(|f|ln)|print|println)$"]
        - pattern: "^(fmt\\.Print(|f|ln)|print|println)$"
          msg: Do not use fmt.Print, fmt,Printf and fmt.Println for log output.
        - pattern: ^print(ln)?$
          msg: Do not use print() for log output.
      exclude-godoc-examples: true
      analyze-types: false
    # forcetypeassert:
    # funcorder:
    # funlen:
    # ginkgolinter:
    # gocheckcompilerdirectives:
    # gochecknoglobals:
    # gochecknoinits:
    # gochecksumtype:
    # gocognit:
    # goconst:
    # gocritic:
    # gocyclo:
    # godot:
    # godox:
    # goheader:
    # gomoddirectives:
    # gomodguard:
    # goprintffuncname:
    # gosec:
    # gosmopolitan:
    # govet:
    # grouper:
    # iface:
    # importas:
    # inamedparam:
    # ineffassign:
    # interfacebloat:
    # intrange:
    # ireturn:
    # lll:
    # loggercheck:
    # maintidx:
    # makezero:
    # mirror:
    # misspell:
    # mnd:
    # musttag:
    # nakedret:
    # nestif:
    # nilerr:
    # nilnesserr:
    # nilnil:
    # nlreturn:
    nlreturn:
      block-size: 1
    # noctx:
    # noinlineerr:
    # nolintlint:
    # nonamedreturns:
    # nosprintfhostport:
    # paralleltest:
    # perfsprint:
    # prealloc:
    # predeclared:
    # promlinter:
    # protogetter:
    # reassign:
    # recvcheck:
    # revive:
    # rowserrcheck:
    # sloglint:
    # spancheck:
    # sqlclosecheck:
    # staticcheck:
    # tagalign:
    # tagliatelle:
    # testableexamples:
    # testifylint:
    # testpackage:
    # thelper:
    # tparallel:
    # unconvert:
    # unparam:
    # unused:
    # usestdlibvars:
    # usetesting:
    # varnamelen:
    # wastedassign:
    # whitespace:
    # wrapcheck:
    # wsl:
    # wsl_v5:
    # zerologlint:
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  uniq-by-line: true
  new: false
  new-from-merge-base: ""
  new-from-rev: ""
  new-from-patch: ""
  whole-files: false
  fix: false
output:
  formats:
    json:
      path: stdout
  path-prefix: ""
  path-mode: ""
  sort-order:
    - linter
    - severity
    - file
  show-stats: true
run:
  timeout: 5m # Default: 0 (disabled)
  relative-path-mode: gomod # Default: cfg
  issues-exit-code: 1
  tests: true
  build-tags: # Default: []
    - mytag
  modules-download-mode: readonly # Default: ""
  allow-parallel-runners: false
  allow-serial-runners: false
  go: '1.25'
  concurrency: 0
severity:
  default: error # Default: ""
  rules: []