name: go-password-keeper

services:
  server:
    container_name: server
    image: filatik/go-password-keeper/server:dev
    build:
      context: ../.. # root with sources (go.mod, cmd/)
      dockerfile: deploy/docker/Dockerfile.server
    restart: unless-stopped

    #environment:                                       # 👈 общие переменные окружения
    #  - APP_ENV=development
    #  - APP_NAME=go-password-keeper
    #  - APP_PORT=8080
    #env_file:                                          # 👈 можно подключить .env файл
    #  - ../../.env
    #networks:
    #  - keeper-net                                     # 👈 общая сеть
    #volumes:                                           # 👈 пример, если нужно монтировать конфиги/логи
    #  - ../../config:/app/config
    #  - ../../logs:/app/logs