// Package server Code generated by swaggo/swag. DO NOT EDIT
package server

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/test": {
            "post": {
                "description": "Test handler for developing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developing"
                ],
                "summary": "Test handler",
                "parameters": [
                    {
                        "description": "Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/TestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/TestResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or validation error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Error": {
            "type": "object",
            "required": [
                "id",
                "message",
                "type"
            ],
            "properties": {
                "details": {
                    "description": "Details - additional details about the error.\n\nThis is an optional parameter.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "ID - unique error identifier.\n\nIt is a required parameter.",
                    "type": "string"
                },
                "message": {
                    "description": "Message - main error message.\n\nIt is a required parameter.",
                    "type": "string"
                },
                "type": {
                    "description": "ErrorType - machine-readable error type.\n\nIt is a required parameter.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/ErrorType"
                        }
                    ]
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "required": [
                "error",
                "statusCode"
            ],
            "properties": {
                "error": {
                    "description": "Error - error.\n\nIt is a required parameter.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/Error"
                        }
                    ]
                },
                "statusCode": {
                    "description": "StatusCode - HTTP response status code.\n\nIt is a required parameter.",
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 400
                }
            }
        },
        "ErrorType": {
            "type": "string",
            "enum": [
                "REQUEST_INVALID_FORMAT",
                "REQUEST_VALIDATION_ERROR"
            ],
            "x-enum-varnames": [
                "RequestInvalidFormat",
                "RequestValidationError"
            ]
        },
        "TestRequest": {
            "type": "object",
            "required": [
                "message",
                "number"
            ],
            "properties": {
                "mes": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "number": {
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 100
                }
            }
        },
        "TestResponse": {
            "type": "object",
            "required": [
                "message",
                "number"
            ],
            "properties": {
                "mes": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "number": {
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 100
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Server API",
	Description:      "# go-password-keeper app\r\n\r\nLoading info...",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
