// Package server Code generated by swaggo/swag. DO NOT EDIT
package server

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/test": {
            "get": {
                "description": "Test handler for developing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developing"
                ],
                "summary": "Test handler",
                "parameters": [
                    {
                        "description": "Optional ping request with custom message",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/dto.TestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "$ref": "#/definitions/dto.TestResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request format or validation error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.Error": {
            "type": "object",
            "required": [
                "id",
                "message",
                "type"
            ],
            "properties": {
                "details": {
                    "description": "Details - additional details about the error.\n\nThis is an optional parameter.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "ID - unique error identifier.\n\nIt is a required parameter.",
                    "type": "string"
                },
                "message": {
                    "description": "Message - main error message.\n\nIt is a required parameter.",
                    "type": "string"
                },
                "type": {
                    "description": "ErrorType - machine-readable error type.\n\nIt is a required parameter.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.ErrorType"
                        }
                    ]
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "required": [
                "error",
                "statusCode"
            ],
            "properties": {
                "error": {
                    "description": "Error - error.\n\nIt is a required parameter.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Error"
                        }
                    ]
                },
                "statusCode": {
                    "description": "StatusCode - HTTP response status code.\n\nIt is a required parameter.",
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 400
                }
            }
        },
        "dto.ErrorType": {
            "type": "string",
            "enum": [
                "REQUEST_INVALID_FORMAT",
                "REQUEST_VALIDATION_ERROR"
            ],
            "x-enum-varnames": [
                "RequestInvalidFormat",
                "RequestValidationError"
            ]
        },
        "dto.TestRequest": {
            "type": "object",
            "required": [
                "message",
                "number"
            ],
            "properties": {
                "mes": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "number": {
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 100
                }
            }
        },
        "dto.TestResponse": {
            "type": "object",
            "required": [
                "message",
                "number"
            ],
            "properties": {
                "mes": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "number": {
                    "type": "integer",
                    "maximum": 599,
                    "minimum": 100
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "tags": [
        {
            "description": "# Admin TAG NO API documentation\r\n\r\n**Admin** NO functions goes here \r\n\r\nFor NO more info please read [link](/docs/readme.md).",
            "name": "server_desc"
        }
    ],
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API 1",
	Description:      "# Admin TAG API documentation\r\n\r\n**Admin** functions goes here \r\n\r\nFor more info please read [link](/docs/readme.md).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
