definitions:
  Error:
    properties:
      details:
        description: |-
          Details - additional details about the error.

          This is an optional parameter.
        items:
          type: string
        type: array
      id:
        description: |-
          ID - unique error identifier.

          It is a required parameter.
        type: string
      message:
        description: |-
          Message - main error message.

          It is a required parameter.
        type: string
      type:
        allOf:
        - $ref: '#/definitions/ErrorType'
        description: |-
          ErrorType - machine-readable error type.

          It is a required parameter.
    required:
    - id
    - message
    - type
    type: object
  ErrorResponse:
    properties:
      error:
        allOf:
        - $ref: '#/definitions/Error'
        description: |-
          Error - error.

          It is a required parameter.
      statusCode:
        description: |-
          StatusCode - HTTP response status code.

          It is a required parameter.
        maximum: 599
        minimum: 400
        type: integer
    required:
    - error
    - statusCode
    type: object
  ErrorType:
    enum:
    - REQUEST_INVALID_FORMAT
    - REQUEST_VALIDATION_ERROR
    type: string
    x-enum-varnames:
    - RequestInvalidFormat
    - RequestValidationError
  TestRequest:
    properties:
      mes:
        type: string
      message:
        type: string
      number:
        maximum: 599
        minimum: 100
        type: integer
    required:
    - message
    - number
    type: object
  TestResponse:
    properties:
      mes:
        type: string
      message:
        type: string
      number:
        maximum: 599
        minimum: 100
        type: integer
    required:
    - message
    - number
    type: object
info:
  contact: {}
  description: "# go-password-keeper app\r\n\r\nLoading info..."
  title: Server API
  version: "1.0"
paths:
  /test:
    post:
      consumes:
      - application/json
      description: Test handler for developing
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/TestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/TestResponse'
        "400":
          description: Invalid request format or validation error
          schema:
            $ref: '#/definitions/ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Test handler
      tags:
      - developing
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
