{
 "title": "Applications Info",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Threads Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (\r\n  go_threads{\r\n    job=~\"server\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (\r\n  go_goroutines{\r\n    job=~\"server\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (\r\n  rate(\r\n    process_cpu_seconds_total{\r\n      job=~\"server\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  process_resident_memory_bytes{\r\n    job=~\"server\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}