apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: filatik-logs-*
    basicAuth: false
    isDefault: false
    jsonData:
      timeField: "@timestamp"
      logMessageField: "msg"
      logLevelField: "level"