name: file-changes-labeler

on:
  pull_request_target:

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Setup labels
      uses: actions/labeler@v5
      with:
        configuration-path: .github/configs/.labeler.yml
        sync-labels: true
